---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nominatim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nominatim
  labels:
    app: datamart
    what: nominatim
spec:
  selector:
    app: datamart
    what: nominatim
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nominatim
  labels:
    app: datamart
    what: nominatim
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: datamart
      what: nominatim
  template:
    metadata:
      labels:
        app: datamart
        what: nominatim
    spec:
      initContainers:
      - name: download-data
        image: remram/nominatim:3.3
        command:
        - "sh"
        - "-c"
        - |
          if ! [ -d /data/base ]; then
            curl -Ls https://www.googleapis.com/download/storage/v1/b/nominatim-data-nyu/o/nominatim-postgres-data.tar?alt=media | tar -C /data --strip-components=1 -xf -
          fi
        volumeMounts:
        - mountPath: /data
          name: data
      containers:
      - name: nominatim
        image: remram/nominatim:3.3
        args: ["bash", "/app/start.sh"]
        ports:
        - containerPort: 5432
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/lib/postgresql/11/main
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nominatim
