FROM python:3.8

ENV TINI_VERSION v0.18.0
RUN curl -Lo /tini https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini && \
    chmod +x /tini

ENV PYTHONFAULTHANDLER=1

RUN mkdir -p /usr/src/app/home && \
    useradd -d /usr/src/app/home -s /usr/sbin/nologin -u 998 appuser && \
    chown appuser /usr/src/app/home
WORKDIR /usr/src/app
RUN pip --disable-pip-version-check --no-cache-dir install toml
COPY docker/install_deps.py poetry.lock /usr/src/app/
RUN python -c "import json, toml; json.dump(toml.load(open('poetry.lock')), open('poetry.lock.json', 'w'))"
RUN python3 install_deps.py poetry.lock.json

COPY --chown=appuser lib_core lib_core
RUN pip --disable-pip-version-check --no-cache-dir install --no-deps -e /usr/src/app/lib_core
COPY --chown=appuser lib_fslock lib_fslock
RUN pip --disable-pip-version-check --no-cache-dir install --no-deps -e /usr/src/app/lib_fslock
COPY --chown=appuser discovery/zenodo /usr/src/app/zenodo
RUN pip --disable-pip-version-check --no-cache-dir install --no-deps -e /usr/src/app/zenodo

RUN python -m compileall /usr/src/app/
ARG version
ENV DATAMART_VERSION ${version}
RUN test -n "${DATAMART_VERSION}"
USER 998
ENTRYPOINT ["/tini", "--"]
CMD ["python", "-m", "zenodo_discovery"]
