{
 "title": "Processes",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Elasticsearch CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_process_cpu_time_seconds_sum{type=\"total\"}[5m])) by (type)"
    }
   ]
  },
  {
   "title": "Elasticsearch memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_jvm_memory_used_bytes) by (area)",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Elasticsearch cluster health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_status{color=\"red\"})",
     "legendFormat": "red"
    },
    {
     "expr": "sum(elasticsearch_cluster_health_status{color!=\"red\"}) by (color)",
     "legendFormat": "{{color}}"
    }
   ]
  },
  {
   "title": "Profiler CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"profiler\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Profiler memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"profiler\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"query\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"query\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "haproxy_backend_active_servers", "legendFormat": "{{proxy}}" }
   ]
  },
  {
   "title": "Number of processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(process_resident_memory_bytes{job=\"coordinator\"}) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "count(process_resident_memory_bytes{job=\"query\"}) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "count(process_resident_memory_bytes{job=\"profiler\"}) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "count(process_resident_memory_bytes{job=\"elasticsearch\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Container versions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(version) by (version, job)",
     "legendFormat": "{{job}} {{version}}"
    }
   ]
  }
 ]
}