{
 "title": "Profiling",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Profile queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"profile\"}",
     "legendFormat": "today"
    },
    {
     "expr": "rabbitmq_queue_messages{queue=\"profile\"} offset 1d",
     "legendFormat": "yesterday"
    }
   ]
  },
  {
   "title": "Median download/profile time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(download_seconds_bucket{job=\"profiler\"}[2h])) without (instance))",
     "legendFormat": "download"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(profile_seconds_bucket{job=\"profiler\"}[2h])) without (instance))",
     "legendFormat": "profile"
    }
   ]
  },
  {
   "title": "90% percentile download/profile time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(download_seconds_bucket{job=\"profiler\"}[2h])) without (instance))",
     "legendFormat": "download"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(profile_seconds_bucket{job=\"profiler\"}[2h])) without (instance))",
     "legendFormat": "profile"
    }
   ]
  },
  {
   "title": "Profiling time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(profile_seconds_bucket{job=\"profiler\"}[1m])) without (instance) * 60",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Datasets by source",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sort(sum(source_count) without (job, instance))"
    }
   ]
  },
  {
   "title": "Datasets by source",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(source_count) without (job, instance)",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}