{
 "title": "Caching",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Lock acquisition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(cache_lock_acquire_seconds_bucket[10m])) without (instance))",
     "legendFormat": "Median {{type}} lock acquisition"
    }
   ]
  },
  {
   "title": "Number of locks held",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cache_locks_held",
     "legendFormat": "{{type}} | {{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Number of cache entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "cache_datasets_count", "legendFormat": "Datasets" },
    { "expr": "cache_augmentations_count", "legendFormat": "Augmentations" }
   ]
  },
  {
   "title": "Cache disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "cache_datasets_bytes", "legendFormat": "Datasets" },
    { "expr": "cache_augmentations_bytes", "legendFormat": "Augmentations" }
   ]
  },
  {
   "title": "Dataset hits/misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_hits_total{cache_dir=\"/cache/datasets\"}[10m])) * 600",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(rate(cache_misses_total{cache_dir=\"/cache/datasets\"}[10m])) * 600",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Query data profile hits/misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_hits_total{cache_dir=\"/cache/queries\"}[10m])) * 600",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(rate(cache_misses_total{cache_dir=\"/cache/queries\"}[10m])) * 600",
     "legendFormat": "Misses"
    }
   ]
  }
 ]
}