{
 "title": "Lazo Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Lazo Memory (JVM Heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\"}",
     "legendFormat": "JVM Used Heap"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\"}",
     "legendFormat": "JVM  Max Heap"
    }
   ]
  },
  {
   "title": "Lazo - CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"lazo\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lazo Request Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(lazo_requests_seconds_count) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Lazo - Total Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(lazo_requests_total) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}