{
 "title": "Node",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=~\"system|user\"}[1m])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes",
     "legendFormat": "available"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "total" }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load1" },
    { "expr": "node_load5", "legendFormat": "load5" },
    { "expr": "node_load15", "legendFormat": "load15" }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[1m])) by (device)",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "-sum(rate(node_disk_written_bytes_total[1m])) by (device)",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Filesystems space available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=~\"/dev/.*\",mountpoint!~\"/boot/.*\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_network_receive_bytes_total{device=~\"en.*\"}[1m])) by (instance)",
     "legendFormat": "recv"
    },
    {
     "expr": "-avg(rate(node_network_transmit_bytes_total{device=~\"en.*\"}[1m])) by (instance, device)",
     "legendFormat": "send"
    }
   ]
  }
 ]
}