{
 "title": "Requests per minute",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Elasticsearch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_total[5m]) * 60",
     "legendFormat": "requests per minute"
    }
   ]
  },
  {
   "title": "/search",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(req_search_count_total[1m]))*60",
     "legendFormat": "requests per minute"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(req_search_seconds_bucket{job=\"query\"}[1h])) without (instance))",
     "legendFormat": "median time"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(req_search_seconds_bucket{job=\"query\"}[1h])) without (instance))",
     "legendFormat": "90% time"
    }
   ]
  },
  {
   "title": "/download",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(req_download_count_total[1m]))*60",
     "legendFormat": "requests per minute (POST)"
    },
    {
     "expr": "sum(rate(req_download_id_count_total[1m]))*60",
     "legendFormat": "requests per minute (GET id)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(req_download_seconds_bucket{job=\"query\"}[1h])) without (instance))",
     "legendFormat": "median time"
    }
   ]
  },
  {
   "title": "/metadata",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(req_metadata_count_total[1m]))*60",
     "legendFormat": "requests per minute"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(req_metadata_seconds_bucket{job=\"query\"}[1h])) without (instance))",
     "legendFormat": "median time"
    }
   ]
  },
  {
   "title": "/augment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(req_augment_count_total[1m]))*60",
     "legendFormat": "requests per minute"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(req_augment_seconds_bucket{job=\"query\"}[1h])) without (instance))",
     "legendFormat": "median time"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(req_augment_seconds_bucket{job=\"query\"}[1h])) without (instance))",
     "legendFormat": "90% time"
    }
   ]
  }
 ]
}